/**
 * Curated homestay records for popular hill stations including Lava, Kurseong, Ravangla,
 * Rishop, Tinchuley, Lepchajagat, Lolegaon, and Sillery Gaon.
 * These are guaranteed to exist in the database and be instantly searchable.
 */

import { ClaimStatus } from "../types";

export interface CuratedHomestay {
  id: string;
  name: string;
  homestay_name: string;
  destinationId: string;
  village_code: string;
  village: string;
  village_name: string;
  district: string;
  district_name: string;
  state: string;
  address: string;
  description: string;
  tagline: string;
  ownerName: string;
  owner_name: string;
  contact: string;
  phone: string;
  priceMin: number;
  priceMax: number;
  price_per_night: number;
  rating: number;
  reviewCount: number;
  verified: boolean;
  isVerified: boolean;
  status: string;
  is_public: boolean;
  claim_status: ClaimStatus;
  amenities: string[];
  images: string[];
  latitude: number;
  longitude: number;
  foodIncluded?: boolean;
  breakfastIncluded?: 'Included' | 'Not Included' | string;
}

export const CURATED_HOMESTAYS: CuratedHomestay[] = [
  // ================= LAVA (Kalimpong District) =================
  {
    id: "HS-LAVA-001",
    name: "Lava Pine Forest Homestay",
    homestay_name: "Lava Pine Forest Homestay",
    destinationId: "306286",
    village_code: "306286",
    village: "Lava",
    village_name: "Lava Bazar",
    district: "Kalimpong",
    district_name: "Kalimpong",
    state: "West Bengal",
    address: "Near Lava Monastery, Main Bazar Road, Lava, Kalimpong - 734319",
    description: "Nestled amidst pristine pine and fir forests at 7,019 ft, offering breathtaking views of Mt. Kanchenjunga, authentic home-cooked Nepali cuisine, and bird-watching trails into Neora Valley.",
    tagline: "Serene pine woods & misty Kanchenjunga views in Lava",
    ownerName: "Dawa Tshering Lepcha",
    owner_name: "Dawa Tshering Lepcha",
    contact: "+91 98320 12341",
    phone: "+91 98320 12341",
    priceMin: 1500,
    priceMax: 2800,
    price_per_night: 1800,
    rating: 4.8,
    reviewCount: 34,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Free Wi-Fi", "Home Cooked Meals", "Hot Water", "Mountain View", "Campfire", "Guided Forest Walk"],
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 27.0864,
    longitude: 88.6601,
    foodIncluded: true,
    breakfastIncluded: 'Included'
  },
  {
    id: "HS-LAVA-002",
    name: "Neora Valley Jungle Camp & Homestay",
    homestay_name: "Neora Valley Jungle Camp & Homestay",
    destinationId: "306286",
    village_code: "306286",
    village: "Lava",
    village_name: "Lava Forest Gate",
    district: "Kalimpong",
    district_name: "Kalimpong",
    state: "West Bengal",
    address: "Neora Valley National Park Entry Gate, Lava, Kalimpong - 734319",
    description: "Eco-friendly wooden cottages on the border of Neora Valley National Park. Ideal for birdwatchers, trekkers, and nature lovers seeking peace in the alpine canopy.",
    tagline: "Wilderness gateway at Neora Valley National Park, Lava",
    ownerName: "Pemba Norbu Sherpa",
    owner_name: "Pemba Norbu Sherpa",
    contact: "+91 97330 45672",
    phone: "+91 97330 45672",
    priceMin: 1800,
    priceMax: 3200,
    price_per_night: 2200,
    rating: 4.9,
    reviewCount: 42,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Bird Watching Guide", "Campfire", "Organic Meals", "Balcony View", "Hot Water"],
    images: [
      "https://images.unsplash.com/photo-1587061949409-02df41d5e562?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 27.0912,
    longitude: 88.6654,
    foodIncluded: true,
    breakfastIncluded: 'Included'
  },
  {
    id: "HS-LAVA-003",
    name: "Lava Monastery View Eco Homestay",
    homestay_name: "Lava Monastery View Eco Homestay",
    destinationId: "306286",
    village_code: "306286",
    village: "Lava",
    village_name: "Lava Monastery Ridge",
    district: "Kalimpong",
    district_name: "Kalimpong",
    state: "West Bengal",
    address: "Upper Ridge Road, Opposite Kagyu Thekchen Ling Monastery, Lava, Kalimpong",
    description: "Wake up to Buddhist morning chants and panoramic sunrise vistas over the Himalayan peaks. Traditional wooden interiors with modern hospitality.",
    tagline: "Overlooking Kagyu Thekchen Ling Monastery in Lava",
    ownerName: "Tashi Bhutia",
    owner_name: "Tashi Bhutia",
    contact: "+91 94340 78910",
    phone: "+91 94340 78910",
    priceMin: 1400,
    priceMax: 2600,
    price_per_night: 1700,
    rating: 4.7,
    reviewCount: 29,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Mountain View", "Monastery Chants", "Local Organic Food", "Wi-Fi", "Geyser"],
    images: [
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 27.0845,
    longitude: 88.6589,
    foodIncluded: true
  },
  {
    id: "HS-LAVA-004",
    name: "Misty Woods Homestay Lava",
    homestay_name: "Misty Woods Homestay Lava",
    destinationId: "306286",
    village_code: "306286",
    village: "Lava",
    village_name: "Upper Lava",
    district: "Kalimpong",
    district_name: "Kalimpong",
    state: "West Bengal",
    address: "Algarah-Lava Road, Upper Lava, Kalimpong District",
    description: "Surrounded by silver firs and rhododendrons, Misty Woods Homestay provides warm Himalayan hospitality with cozy rooms and bonfire evenings.",
    tagline: "Cozy rooms & pine forest fog in Upper Lava",
    ownerName: "Sonam Tamang",
    owner_name: "Sonam Tamang",
    contact: "+91 96478 33211",
    phone: "+91 96478 33211",
    priceMin: 1300,
    priceMax: 2400,
    price_per_night: 1600,
    rating: 4.6,
    reviewCount: 21,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Bonfire", "Garden", "Parking", "Tea Maker", "Geyser"],
    images: [
      "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 27.088,
    longitude: 88.662
  },
  {
    id: "HS-LAVA-005",
    name: "Kanchan Kanya Mountain Homestay Lava",
    homestay_name: "Kanchan Kanya Mountain Homestay Lava",
    destinationId: "306286",
    village_code: "306286",
    village: "Lava",
    village_name: "Lava Forest Beat",
    district: "Kalimpong",
    district_name: "Kalimpong",
    state: "West Bengal",
    address: "Near Forest Inspection Bungalow, Lava, Kalimpong",
    description: "Clear sunrise views of Kanchenjunga range, birdwatching trails, and warm home cooked meals with locally cultivated vegetables.",
    tagline: "Golden sunrise over snowy peaks in Lava",
    ownerName: "Bimal Pradhan",
    owner_name: "Bimal Pradhan",
    contact: "+91 98322 99011",
    phone: "+91 98322 99011",
    priceMin: 1500,
    priceMax: 2700,
    price_per_night: 1900,
    rating: 4.8,
    reviewCount: 38,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Balcony", "Sunrise Point", "Home Cooking", "Hot Water", "Wi-Fi"],
    images: [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 27.085,
    longitude: 88.657
  },

  // ================= KURSEONG (Darjeeling District) =================
  {
    id: "HS-KURSEONG-001",
    name: "Makaibari Tea Estate Eco Homestay Kurseong",
    homestay_name: "Makaibari Tea Estate Eco Homestay Kurseong",
    destinationId: "99992",
    village_code: "99992",
    village: "Kurseong",
    village_name: "Makaibari Tea Garden",
    district: "Darjeeling",
    district_name: "Darjeeling",
    state: "West Bengal",
    address: "Makaibari Tea Estate, Kurseong, Darjeeling - 734203",
    description: "Stay in the world's oldest tea factory estate run by warm tea-plucker families. Experience world-class Darjeeling tea tasting, organic garden tours, and heritage train sights.",
    tagline: "Authentic tea plucker homestay in Makaibari, Kurseong",
    ownerName: "Devi Maya Rai",
    owner_name: "Devi Maya Rai",
    contact: "+91 98324 77651",
    phone: "+91 98324 77651",
    priceMin: 1600,
    priceMax: 3000,
    price_per_night: 2000,
    rating: 4.9,
    reviewCount: 56,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Tea Garden Tour", "Tea Tasting", "Home Cooked Meals", "Hot Water", "Verandah"],
    images: [
      "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1563911302283-d2bc129e7570?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 26.8812,
    longitude: 88.2789,
    foodIncluded: true,
    breakfastIncluded: 'Included'
  },
  {
    id: "HS-KURSEONG-002",
    name: "Eagles Crag View Homestay Kurseong",
    homestay_name: "Eagles Crag View Homestay Kurseong",
    destinationId: "99992",
    village_code: "99992",
    village: "Kurseong",
    village_name: "Eagles Crag Ridge",
    district: "Darjeeling",
    district_name: "Darjeeling",
    state: "West Bengal",
    address: "Near Eagle's Crag Viewpoint, Hill Cart Road, Kurseong - 734203",
    description: "Perched atop the highest cliff of Kurseong town, offering sweeping views of the Siliguri plains, Teesta river valleys, and snow-capped Kanchenjunga peaks.",
    tagline: "Panoramic cliff views over Kurseong valleys & plains",
    ownerName: "Subhash Chettri",
    owner_name: "Subhash Chettri",
    contact: "+91 94344 11234",
    phone: "+91 94344 11234",
    priceMin: 1400,
    priceMax: 2600,
    price_per_night: 1750,
    rating: 4.7,
    reviewCount: 31,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Valley View Balcony", "Free Wi-Fi", "Homemade Food", "Hot Shower", "Terrace"],
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 26.8835,
    longitude: 88.281,
    foodIncluded: true
  },
  {
    id: "HS-KURSEONG-003",
    name: "Dowhill Pine Retreat Homestay Kurseong",
    homestay_name: "Dowhill Pine Retreat Homestay Kurseong",
    destinationId: "99992",
    village_code: "99992",
    village: "Kurseong",
    village_name: "Dowhill Forest",
    district: "Darjeeling",
    district_name: "Darjeeling",
    state: "West Bengal",
    address: "Dowhill Road, Near Victoria Boys School, Kurseong, Darjeeling",
    description: "Bordering the mystical Dowhill pine and cedar forest, this British colonial era homestay provides cozy wooden fireplaces and heritage charm.",
    tagline: "Colonial heritage charm in Dowhill Pine Forest, Kurseong",
    ownerName: "Anand Gurung",
    owner_name: "Anand Gurung",
    contact: "+91 97331 88902",
    phone: "+91 97331 88902",
    priceMin: 1700,
    priceMax: 3200,
    price_per_night: 2100,
    rating: 4.8,
    reviewCount: 45,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Fireplace", "Forest Walk", "Library", "Organic Tea", "Hot Water"],
    images: [
      "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 26.892,
    longitude: 88.288,
    foodIncluded: true
  },
  {
    id: "HS-KURSEONG-004",
    name: "White Orchid Kurseong Homestay",
    homestay_name: "White Orchid Kurseong Homestay",
    destinationId: "99992",
    village_code: "99992",
    village: "Kurseong",
    village_name: "Kurseong Town",
    district: "Darjeeling",
    district_name: "Darjeeling",
    state: "West Bengal",
    address: "T.N. Road, Near DHR Toy Train Station, Kurseong - 734203",
    description: "Located within walking distance of the historic Kurseong Toy Train station, known as the Land of White Orchids.",
    tagline: "Heritage Toy Train accessibility in Kurseong",
    ownerName: "Pooja Thapa",
    owner_name: "Pooja Thapa",
    contact: "+91 98320 54321",
    phone: "+91 98320 54321",
    priceMin: 1200,
    priceMax: 2200,
    price_per_night: 1500,
    rating: 4.6,
    reviewCount: 27,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Station Pickup", "Wi-Fi", "Hot Water", "Home Cooked Meals"],
    images: [
      "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 26.88,
    longitude: 88.277
  },
  {
    id: "HS-KURSEONG-005",
    name: "Chimney Heritage Homestay Kurseong",
    homestay_name: "Chimney Heritage Homestay Kurseong",
    destinationId: "99992",
    village_code: "99992",
    village: "Kurseong",
    village_name: "Chimney Village",
    district: "Darjeeling",
    district_name: "Darjeeling",
    state: "West Bengal",
    address: "Chimney Village, Upper Kurseong Ridge, Darjeeling - 734203",
    description: "Built around the historical 100-year-old First World War Chimney viewpoint. Quiet village tranquility with mountain spring water and rhododendron woods.",
    tagline: "Historic WWI Chimney viewpoint stay in Kurseong",
    ownerName: "Laxman Subba",
    owner_name: "Laxman Subba",
    contact: "+91 98329 88123",
    phone: "+91 98329 88123",
    priceMin: 1500,
    priceMax: 2800,
    price_per_night: 1850,
    rating: 4.8,
    reviewCount: 36,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Campfire", "Sunset View", "Farm-fresh Dairy", "Geyser"],
    images: [
      "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 26.898,
    longitude: 88.293
  },

  // ================= RAVANGLA (Namchi District, South Sikkim) =================
  {
    id: "HS-RAVANGLA-001",
    name: "Buddha Park View Homestay Ravangla",
    homestay_name: "Buddha Park View Homestay Ravangla",
    destinationId: "260925",
    village_code: "260925",
    village: "Ravangla",
    village_name: "Rabong",
    district: "Namchi",
    district_name: "Namchi",
    state: "Sikkim",
    address: "Buddha Park Road, Ravangla, Namchi District, Sikkim - 737139",
    description: "Overlooking the majestic 130-foot statue of Buddha Shakyamuni at Tathagata Tsal, backdropped by Mt. Narsing and Mt. Kanchenjunga.",
    tagline: "Spectacular direct view of Tathagata Tsal Buddha Park in Ravangla",
    ownerName: "Karma Wangchuk Bhutia",
    owner_name: "Karma Wangchuk Bhutia",
    contact: "+91 97330 99881",
    phone: "+91 97330 99881",
    priceMin: 1600,
    priceMax: 3000,
    price_per_night: 2100,
    rating: 4.9,
    reviewCount: 62,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Buddha Park View", "Traditional Sikkimese Food", "Free Wi-Fi", "Hot Water", "Balcony"],
    images: [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 27.3075,
    longitude: 88.3631,
    foodIncluded: true
  },
  {
    id: "HS-RAVANGLA-002",
    name: "Rayong Sunrise Eco Homestay Ravangla",
    homestay_name: "Rayong Sunrise Eco Homestay Ravangla",
    destinationId: "260925",
    village_code: "260925",
    village: "Ravangla",
    village_name: "Rayong View Point",
    district: "Namchi",
    district_name: "Namchi",
    state: "Sikkim",
    address: "Rayong Sunrise Viewpoint, Ravangla-Damthang Road, Sikkim",
    description: "Witness the first golden rays of sunlight lighting up the snow peaks of Eastern Himalayas, combined with organic cardamom tea.",
    tagline: "Captivating mountain sunrise & cardamom orchards in Ravangla",
    ownerName: "Passang Dorjee Lepcha",
    owner_name: "Passang Dorjee Lepcha",
    contact: "+91 98325 33412",
    phone: "+91 98325 33412",
    priceMin: 1400,
    priceMax: 2600,
    price_per_night: 1800,
    rating: 4.8,
    reviewCount: 39,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Sunrise Balcony", "Organic Cardamom Tea", "Bonfire", "Hot Water"],
    images: [
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 27.315,
    longitude: 88.37
  },
  {
    id: "HS-RAVANGLA-003",
    name: "Ralang Monastery Road Village Homestay Ravangla",
    homestay_name: "Ralang Monastery Road Village Homestay Ravangla",
    destinationId: "260925",
    village_code: "260925",
    village: "Ravangla",
    village_name: "Ralang",
    district: "Namchi",
    district_name: "Namchi",
    state: "Sikkim",
    address: "Old Ralang Road, Near Ralang Monastery, Ravangla, South Sikkim",
    description: "Traditional Sikkimese stone house with wooden interiors near Ralang Monastery. Organic vegetables from family terrace fields.",
    tagline: "Peaceful monastery trail and authentic organic farm in Ravangla",
    ownerName: "Chung Chung Bhutia",
    owner_name: "Chung Chung Bhutia",
    contact: "+91 94348 22190",
    phone: "+91 94348 22190",
    priceMin: 1500,
    priceMax: 2800,
    price_per_night: 1900,
    rating: 4.8,
    reviewCount: 30,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Organic Farm", "Monastery Walk", "Hot Water", "Traditional Kitchen"],
    images: [
      "https://images.unsplash.com/photo-1587061949409-02df41d5e562?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 27.298,
    longitude: 88.35
  },

  // ================= RISHOP / RISHYAP (Kalimpong District) =================
  {
    id: "HS-RISHOP-001",
    name: "Rishyap Tiffin Dara View Homestay",
    homestay_name: "Rishyap Tiffin Dara View Homestay",
    destinationId: "306286",
    village_code: "306286",
    village: "Rishop",
    village_name: "Rishyap Hamlet",
    district: "Kalimpong",
    district_name: "Kalimpong",
    state: "West Bengal",
    address: "Upper Rishyap, Near Tiffin Dara Trail, Kalimpong - 734319",
    description: "360-degree panorama of Kanchenjunga, Mt. Pandim, and Kabru from the quiet village of Rishop at 8,500 ft. A trekker's paradise 4 km above Lava.",
    tagline: "Unrivaled 360-degree Kanchenjunga panorama in Rishop",
    ownerName: "Norbu Tshering Sherpa",
    owner_name: "Norbu Tshering Sherpa",
    contact: "+91 98327 11440",
    phone: "+91 98327 11440",
    priceMin: 1500,
    priceMax: 2800,
    price_per_night: 1950,
    rating: 4.9,
    reviewCount: 48,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Tiffin Dara Trek", "360 Degree View", "Campfire", "Home Cooked Food", "Hot Water"],
    images: [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 27.108,
    longitude: 88.648
  },

  // ================= TINCHULEY (Darjeeling District) =================
  {
    id: "HS-TINCHULEY-001",
    name: "Tinchuley Gurung Guest House & Homestay",
    homestay_name: "Tinchuley Gurung Guest House & Homestay",
    destinationId: "306235",
    village_code: "306235",
    village: "Tinchuley",
    village_name: "Tinchuley",
    district: "Darjeeling",
    district_name: "Darjeeling",
    state: "West Bengal",
    address: "Tinchuley Village, Takdah Cantonment, Darjeeling - 734222",
    description: "The pioneer of eco-tourism in Tinchuley. Surrounded by orange orchards, tea gardens, and pine forests with views of the snow ranges.",
    tagline: "Pioneer eco-tourism homestay in scenic Tinchuley",
    ownerName: "Dipendra Gurung",
    owner_name: "Dipendra Gurung",
    contact: "+91 98320 88231",
    phone: "+91 98320 88231",
    priceMin: 1600,
    priceMax: 3000,
    price_per_night: 2000,
    rating: 4.9,
    reviewCount: 74,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Orange Orchards", "Tea Garden Walk", "Organic Food", "Bonfire", "Free Wi-Fi"],
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 27.025,
    longitude: 88.36
  },

  // ================= LEPCHAJAGAT (Darjeeling District) =================
  {
    id: "HS-LEPCHAJAGAT-001",
    name: "Lepchajagat Pine Whisper Homestay",
    homestay_name: "Lepchajagat Pine Whisper Homestay",
    destinationId: "306662",
    village_code: "306662",
    village: "Lepchajagat",
    village_name: "Lepchajagat Forest",
    district: "Darjeeling",
    district_name: "Darjeeling",
    state: "West Bengal",
    address: "Near WBFDC Lodge, Lepchajagat, Sukhiapokhri, Darjeeling - 734221",
    description: "Hidden in dense oak and pine reserve forests at 6,956 ft. Famous for serene solitude, birdlife, and the grandest Kanchenjunga view at dawn.",
    tagline: "Dense oak forest tranquility & Kanchenjunga in Lepchajagat",
    ownerName: "Kinzang Lepcha",
    owner_name: "Kinzang Lepcha",
    contact: "+91 94340 55123",
    phone: "+91 94340 55123",
    priceMin: 1500,
    priceMax: 2700,
    price_per_night: 1800,
    rating: 4.8,
    reviewCount: 51,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Forest Trail", "Bird Watching", "Bonfire", "Hot Water", "Local Meals"],
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 27.009,
    longitude: 88.201
  },

  // ================= LOLEGAON (Kalimpong District) =================
  {
    id: "HS-LOLEGAON-001",
    name: "Lolegaon Canopy Walk Nature Homestay",
    homestay_name: "Lolegaon Canopy Walk Nature Homestay",
    destinationId: "306286",
    village_code: "306286",
    village: "Lolegaon",
    village_name: "Kafer Village",
    district: "Kalimpong",
    district_name: "Kalimpong",
    state: "West Bengal",
    address: "Near Canopy Hanging Bridge, Lolegaon, Kalimpong - 734319",
    description: "Located close to the famous hanging canopy footbridge inside ancient moss-covered cypress woods. Unspoilt nature and bird songs.",
    tagline: "Cypress forest & canopy walk retreat in Lolegaon",
    ownerName: "Mingma Sherpa",
    owner_name: "Mingma Sherpa",
    contact: "+91 98324 11987",
    phone: "+91 98324 11987",
    priceMin: 1400,
    priceMax: 2500,
    price_per_night: 1700,
    rating: 4.7,
    reviewCount: 33,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Canopy Walk", "Cypress Forest", "Home Cooking", "Hot Water"],
    images: [
      "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 27.02,
    longitude: 88.56
  },

  // ================= SILLERY GAON (Kalimpong District) =================
  {
    id: "HS-SILLERY-001",
    name: "Sillery Gaon Nirmala Eco Homestay",
    homestay_name: "Sillery Gaon Nirmala Eco Homestay",
    destinationId: "306286",
    village_code: "306286",
    village: "Sillery Gaon",
    village_name: "Sillery Village",
    district: "Kalimpong",
    district_name: "Kalimpong",
    state: "West Bengal",
    address: "Sillery Gaon, Pedong-Reshi Road, Kalimpong District - 734311",
    description: "Known affectionately as the 'New Darjeeling'. Perched at 6,000 ft with uninterrupted views of Mt. Kanchenjunga and Ramitey viewpoint overlooking 14 turns of River Teesta.",
    tagline: "Scenic New Darjeeling with 14 bends of Teesta in Sillery Gaon",
    ownerName: "Dilip Tamang",
    owner_name: "Dilip Tamang",
    contact: "+91 97332 66710",
    phone: "+91 97332 66710",
    priceMin: 1400,
    priceMax: 2400,
    price_per_night: 1650,
    rating: 4.8,
    reviewCount: 41,
    verified: true,
    isVerified: true,
    status: "Approved",
    is_public: true,
    claim_status: "CLAIMED",
    amenities: ["Ramitey Viewpoint", "Teesta River View", "Bonfire", "Organic Meals"],
    images: [
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80"
    ],
    latitude: 27.14,
    longitude: 88.58
  }
];
