import { LifecycleStateConfig } from '../types/lifecycle';

export const LIFECYCLE_STATES: Record<string, LifecycleStateConfig> = {
  draft: {
    id: 'draft',
    title: 'Draft',
    description: 'The business registration profile is incomplete or in draft mode.',
    color: 'bg-slate-100 text-slate-800 border-slate-200',
    icon: 'FileText',
    isPublic: false,
    canReceiveBookings: false,
    canReceiveMessages: false,
    canEditProfile: true,
    canAppearInSearch: false,
    canReceiveReviews: false,
    canReceivePayments: false,
    allowedTransitions: ['pending_verification', 'deleted']
  },
  pending_verification: {
    id: 'pending_verification',
    title: 'Pending Verification',
    description: 'Verification is ongoing by administrative review teams.',
    color: 'bg-blue-100 text-blue-800 border-blue-200',
    icon: 'ShieldAlert',
    isPublic: false,
    canReceiveBookings: false,
    canReceiveMessages: false,
    canEditProfile: false,
    canAppearInSearch: false,
    canReceiveReviews: false,
    canReceivePayments: false,
    allowedTransitions: ['approved', 'rejected', 'deleted']
  },
  approved: {
    id: 'approved',
    title: 'Approved',
    description: 'Onboarding verification checks complete and approved. Ready to go live.',
    color: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    icon: 'ShieldCheck',
    isPublic: false,
    canReceiveBookings: false,
    canReceiveMessages: true,
    canEditProfile: true,
    canAppearInSearch: false,
    canReceiveReviews: false,
    canReceivePayments: false,
    allowedTransitions: ['published', 'suspended', 'archived']
  },
  published: {
    id: 'published',
    title: 'Published',
    description: 'Business profile is live but not yet active or taking bookings.',
    color: 'bg-teal-100 text-teal-800 border-teal-200',
    icon: 'Globe',
    isPublic: true,
    canReceiveBookings: false,
    canReceiveMessages: true,
    canEditProfile: true,
    canAppearInSearch: true,
    canReceiveReviews: true,
    canReceivePayments: false,
    allowedTransitions: ['active', 'temporarily_unavailable', 'suspended', 'archived']
  },
  active: {
    id: 'active',
    title: 'Active',
    description: 'Operational and online. Ready to upgrade or start receiving trip bookings.',
    color: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    icon: 'Activity',
    isPublic: true,
    canReceiveBookings: false,
    canReceiveMessages: true,
    canEditProfile: true,
    canAppearInSearch: true,
    canReceiveReviews: true,
    canReceivePayments: true,
    allowedTransitions: ['receiving_bookings', 'temporarily_unavailable', 'inactive', 'suspended', 'archived']
  },
  receiving_bookings: {
    id: 'receiving_bookings',
    title: 'Receiving Bookings',
    description: 'Fully active, accepting reservations, and taking online payments.',
    color: 'bg-green-100 text-green-800 border-green-200',
    icon: 'CalendarCheck',
    isPublic: true,
    canReceiveBookings: true,
    canReceiveMessages: true,
    canEditProfile: true,
    canAppearInSearch: true,
    canReceiveReviews: true,
    canReceivePayments: true,
    allowedTransitions: ['active', 'temporarily_unavailable', 'suspended', 'archived']
  },
  temporarily_unavailable: {
    id: 'temporarily_unavailable',
    title: 'Temporarily Unavailable',
    description: 'Offline for maintenance, bad seasonal weather, or host time-off.',
    color: 'bg-amber-100 text-amber-800 border-amber-200',
    icon: 'Clock',
    isPublic: true,
    canReceiveBookings: false,
    canReceiveMessages: true,
    canEditProfile: true,
    canAppearInSearch: true,
    canReceiveReviews: true,
    canReceivePayments: false,
    allowedTransitions: ['active', 'receiving_bookings', 'suspended', 'archived']
  },
  inactive: {
    id: 'inactive',
    title: 'Inactive',
    description: 'The operator manually paused listing operations indefinitely.',
    color: 'bg-slate-300 text-slate-800 border-slate-400',
    icon: 'Moon',
    isPublic: false,
    canReceiveBookings: false,
    canReceiveMessages: false,
    canEditProfile: true,
    canAppearInSearch: false,
    canReceiveReviews: false,
    canReceivePayments: false,
    allowedTransitions: ['active', 'archived']
  },
  rejected: {
    id: 'rejected',
    title: 'Rejected',
    description: 'Onboarding verification failed due to bad or non-compliant credentials.',
    color: 'bg-rose-100 text-rose-800 border-rose-200',
    icon: 'XCircle',
    isPublic: false,
    canReceiveBookings: false,
    canReceiveMessages: false,
    canEditProfile: true,
    canAppearInSearch: false,
    canReceiveReviews: false,
    canReceivePayments: false,
    allowedTransitions: ['draft', 'archived', 'deleted']
  },
  suspended: {
    id: 'suspended',
    title: 'Suspended',
    description: 'Account access locked due to customer complaints or regulatory warnings.',
    color: 'bg-red-100 text-red-800 border-red-200',
    icon: 'AlertOctagon',
    isPublic: false,
    canReceiveBookings: false,
    canReceiveMessages: true,
    canEditProfile: false,
    canAppearInSearch: false,
    canReceiveReviews: true,
    canReceivePayments: false,
    allowedTransitions: ['active', 'approved', 'archived']
  },
  archived: {
    id: 'archived',
    title: 'Archived',
    description: 'Business catalog archived for history and tax compliance.',
    color: 'bg-slate-200 text-slate-800 border-slate-300',
    icon: 'Archive',
    isPublic: false,
    canReceiveBookings: false,
    canReceiveMessages: false,
    canEditProfile: false,
    canAppearInSearch: false,
    canReceiveReviews: false,
    canReceivePayments: false,
    allowedTransitions: ['draft'] // Can be restored under rare administrative needs
  },
  deleted: {
    id: 'deleted',
    title: 'Deleted',
    description: 'Permanently deleted and physically wiped from search indexing pipelines.',
    color: 'bg-neutral-800 text-neutral-300 border-neutral-700',
    icon: 'Trash2',
    isPublic: false,
    canReceiveBookings: false,
    canReceiveMessages: false,
    canEditProfile: false,
    canAppearInSearch: false,
    canReceiveReviews: false,
    canReceivePayments: false,
    allowedTransitions: [] // Terminal stage
  }
};

/**
 * Gets a specific state configuration by its ID.
 */
export const getLifecycleStateConfig = (stateId: string): LifecycleStateConfig | undefined => {
  return LIFECYCLE_STATES[stateId];
};
