// Preserve native browser fetch at top-level before any module or interceptor runs
if (typeof window !== 'undefined' && window.fetch) {
  const w = window as any;
  if (!w.__hillyTrip_realNativeFetch && !window.fetch.hasOwnProperty('isHillyTrip')) {
    w.__hillyTrip_realNativeFetch = window.fetch.bind(window);
  }
}

import {StrictMode} from 'react';
import {createRoot} from 'react-dom/client';

// Immersive Sandboxed Guard: Catch and suppress generic 'Script error.' events
// which are typically generated by blocked third-party analytics or extensions in an iframe
if (typeof window !== 'undefined') {
  // Safe Storage Guard: Intercept Storage.prototype.setItem to safely handle QuotaExceededError
  if (window.Storage) {
    try {
      const originalStorageSetItem = Storage.prototype.setItem;
      Storage.prototype.setItem = function (key: string, value: string) {
        try {
          originalStorageSetItem.call(this, key, value);
        } catch (e: any) {
          console.warn(`[Storage Guard] setItem failed for key "${key}". Evicting stale cache items...`, e);
          try {
            const keysToRemove: string[] = [];
            for (let i = 0; i < this.length; i++) {
              const k = this.key(i);
              if (k && (
                k.startsWith('hillytrip_cache_') || 
                k.startsWith('hilly_cache_') || 
                k.startsWith('hillytrip_cached_') || 
                k.startsWith('hilly_recent_') || 
                k.includes('cache')
              )) {
                keysToRemove.push(k);
              }
            }
            keysToRemove.forEach(k => {
              try { this.removeItem(k); } catch (rmErr) {}
            });
            // Try setting item again after clearing old cache
            originalStorageSetItem.call(this, key, value);
          } catch (retryErr) {
            console.warn(`[Storage Guard] Storage quota full for key "${key}". Action skipped gracefully without app crash.`);
          }
        }
      };
    } catch (e) {}
  }
}

import './utils/apiInterceptor'; // Import API interceptor early for Netlify database fallback compatibility
import App from './App';
import './index.css';
import { BrandingProvider } from './components/BrandingContext';
import ErrorBoundary from './components/ErrorBoundary';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <ErrorBoundary fallbackTitle="HillyTrip Intelligence Portal">
      <BrandingProvider>
        <App />
      </BrandingProvider>
    </ErrorBoundary>
  </StrictMode>,
);

// Register or unregister Service Worker appropriately
if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
  const isDev = Boolean((import.meta as any)?.env?.DEV) || 
    window.location.hostname === 'localhost' || 
    window.location.hostname === '127.0.0.1' ||
    window.location.port === '3000';

  if (isDev) {
    // In local development, proactively unregister any active service worker to prevent stale Vite chunk caching
    navigator.serviceWorker.getRegistrations().then(registrations => {
      for (const registration of registrations) {
        registration.unregister().catch(() => {});
      }
    }).catch(() => {});
    if ('caches' in window) {
      caches.keys().then(names => {
        for (const name of names) {
          if (name.includes('hillytrip')) {
            caches.delete(name).catch(() => {});
          }
        }
      }).catch(() => {});
    }
  } else {
    window.addEventListener('load', () => {
      const isIframe = window.self !== window.top;
      if (isIframe) {
        console.log('[HillyTrip PWA] Service Worker registration bypassed inside sandboxed iframe context.');
        return;
      }
      navigator.serviceWorker.register('/sw.js')
        .then(reg => {
          console.log('[HillyTrip PWA] Service Worker registered in remote hub scope:', reg.scope);
        })
        .catch(err => {
          console.warn('[HillyTrip PWA Warning] Service Worker registration rejected:', err);
        });
    });
  }
}

